//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.26 at 09:32:03 AM WAT 
//

package org.openmrs.module.extractionemr.model.ndr;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for MessageHeaderType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageCreationDateTime" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="MessageUniqueID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="XmlType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="fingerprintsvalidation"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageVersion" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="MessageSendingOrganisation" type="{}MessageSendingOrganisationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageHeaderType", propOrder = { "messageCreationDateTime", "messageUniqueID", "xmlType",
        "messageVersion", "messageSendingOrganisation" })
public class MessageHeaderType {
	
	@XmlElement(name = "MessageCreationDateTime", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar messageCreationDateTime;
	
	@XmlElement(name = "MessageUniqueID", required = true)
	protected String messageUniqueID;
	
	@XmlElement(name = "XmlType", required = true)
	protected String xmlType;
	
	@XmlElement(name = "MessageVersion")
	protected float messageVersion;
	
	@XmlElement(name = "MessageSendingOrganisation", required = true)
	protected FacilityType messageSendingOrganisation;
	
	/**
	 * Gets the value of the messageCreationDateTime property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	public XMLGregorianCalendar getMessageCreationDateTime() {
		return messageCreationDateTime;
	}
	
	/**
	 * Sets the value of the messageCreationDateTime property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	public void setMessageCreationDateTime(XMLGregorianCalendar value) {
		this.messageCreationDateTime = value;
	}
	
	/**
	 * Gets the value of the messageUniqueID property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getMessageUniqueID() {
		return messageUniqueID;
	}
	
	/**
	 * Sets the value of the messageUniqueID property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setMessageUniqueID(String value) {
		this.messageUniqueID = value;
	}
	
	/**
	 * Gets the value of the xmlType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getXmlType() {
		return xmlType;
	}
	
	/**
	 * Sets the value of the xmlType property.
	 * 
	 * @param value allowed object is {@link String }
	 */
	public void setXmlType(String value) {
		this.xmlType = value;
	}
	
	/**
	 * Gets the value of the messageVersion property.
	 */
	public float getMessageVersion() {
		return messageVersion;
	}
	
	/**
	 * Sets the value of the messageVersion property.
	 */
	public void setMessageVersion(float value) {
		this.messageVersion = value;
	}
	
	/**
	 * Gets the value of the messageSendingOrganisation property.
	 * 
	 * @return possible object is {@link FacilityType }
	 */
	public FacilityType getMessageSendingOrganisation() {
		return messageSendingOrganisation;
	}
	
	/**
	 * Sets the value of the messageSendingOrganisation property.
	 * 
	 * @param value allowed object is {@link MessageSendingOrganisationType }
	 */
	public void setMessageSendingOrganisation(FacilityType value) {
		this.messageSendingOrganisation = value;
	}
	
}
